# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-DBI-Pg-More
version:      0.04
version_from: lib/Class/DBI/Pg/More.pm
installdirs:  site
requires:
    Class::DBI::Pg:                0.09
    Class::DBI::Plugin::DateTime::Pg: 
    Test::Simple:                  0.44
    Test::TempDatabase:            0.12

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
